// This file was generated by https://app.quicktype.io/?l=ts by copying the object from dev tool to this website

declare global {
    interface Window {
        appViewModel: any;
    }
}

export interface TransferedPlayer {
    id:              number;
    leagueId:        number;
    value:           number;
    price:           number;
    weekNr:          number;
    startDay:        number;
    sourceTeamId:    number;
    timestamp:       number;
    player:          Player;
    destinationTeam: Team;
    sourceTeam:      Team;
}

export interface PlayerModel {
    id:                             number;
    compNr:                         number;
    type:                           number;
    price:                          number;
    transferPrice:                  number;
    variableFee:                    number;
    boosted:                        number;
    leagueTypeId:                   number;
    player:                         Player;
    team:                           Team;
    countdownTimer:                 null;
    _bossCoinConversionProductName: string;
    _bossCoinFeeProductName:        string;
    isOnList:                       boolean;
    _transferPlayerService:         TransferPlayerService;
}

export interface TransferPlayerService {
}

export interface Player {
    id:                     number;
    assets:                 Asset[];
    fullName:               string;
    name:                   string;
    position:               number;
    specificPosition:       number;
    statAtt:                number;
    statDef:                number;
    statOvr:                number;
    age:                    number;
    teamId:                 number;
    leagueId:               number;
    fitness:                number;
    morale:                 number;
    goals:                  number;
    status:                 number;
    unavailable:            number;
    lineup:                 number;
    value:                  number;
    yellowCards:            number;
    trainingProgress:       number;
    injuryId:               number;
    suspensionId:           number;
    assists:                number;
    lastPlayerGrade:        number;
    averagePlayerGrade:     number;
    lastAveragePlayerGrade: number;
    matchesPlayed:          number;
    goalsLastMatch:         number;
    rarity:                 number;
    nationality:            Nationality;
    squadNumber:            number;
    leagueTypeId:           number;
    team:                   Team | undefined;
}

export interface Nationality {
    id:   number;
    code: string;
    name: string;
}

export interface Team {
    id:              number;
    baseId:          string;
    uniqueId:        string;
    assets:          Asset[];
    leagueId:        number;
    leagueTypeId:    number;
    name:            string;
    city:            string;
    goal:            number;
    stadiumName:     string;
    stadiumCapacity: number;
    ranking:         number;
    stadiumLevel:    number;
    previousRanking: number;
    rankingStatus:   number;
    budget:          number;
    userId:          number;
    crewId:          number;
    baseTeamId:      number;
    isForeignTeam:   boolean;
    poule:           string;
    manager:         Manager;
}

export interface Asset {
    id:    number;
    type:  number;
    value: string;
    path:  string;
}

export interface Manager {
    id:                         number;
    countryCode:                string;
    name:                       string;
    avatarId:                   number;
    leagueId:                   number;
    teamId:                     number;
    signUpTimestamp:            number;
    lastLoginTimestamp:         number;
    lastLoginPlatform:          number;
    masterAccountId:            number;
    partnerNr:                  number;
    wins:                       number;
    losses:                     number;
    total:                      number;
    hasUser:                    boolean;
    resignCount:                number;
    teamStartWeekNr:            number;
    crewId:                     number;
    crewTag:                    string;
    crewRankingDivisionSorting: number;
    crewAvatarId:               number;
    skillRating:                number;
    leagueSkillRating:          number;
}
    

export let posKeys : Record<number,string>={
    0: "Unknown",
    1: "CAM",
    2: "CM",
    3: "CB",
    4: "ST",
    5: "CDM",
    6: "GK",
    7: "LM",
    8: "LW",
    9: "LB",
    10: "RM",
    11: "RW",
    12: "RB",
    // default: "Unknown"
}
